Hi, I’m Grygoriy, I’ve got your offer letter and I...
No, this won’t work... Good day, I’m Grygoriy, I’ve received your offer letter and came here to pass the job interview...
Good day, I’m Grygoriy, I’ve received your offer letter and I came here to find out more about the company and working here. I will also be glad to answer any questions about my qualifications and the skills I possess.
“Just in time”
