name: Deploy Unity WebGL

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (v4, with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true
          
      - name: Download artifact from build
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test-build.yml
          workflow_conclusion: success
          name: WebGL-Build
          path: build/WebGL

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/WebGL/*
          publish_branch: gh-pages